[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "a694fd0f06a65e4650f03c6cb847eb5af8b16382"
libgfortran_version = "5.0.0"
os = "macos"

    [[SHTOOLS.download]]
    sha256 = "efbeffcaee30b4d825223f78f3d71a1288bfde2917b37bcac585f5c9c13d615c"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.aarch64-apple-darwin-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "de42af757bce482f4d6802d736ed2dca5b0eb806"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "4b03391502092fb84acdfcc186201d8ddf1d20e9d90023c475d6d51474fb6eea"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.aarch64-linux-gnu-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "2b1f0d2e88ee993f4e0515d25b7b23c4b3dfaea8"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "573b903d686b7895faa6fff788703b7513f76b54641fcc365d5df343c8486f96"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.aarch64-linux-gnu-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "047e6f20e14555bc6d6c5ccb25c0c5e265099a25"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "507152cb4a3f409f6e7f726ac1608b3651789e7acad11b61c1f5adf287d2432d"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.aarch64-linux-gnu-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "5f6968c9d9e4c13564bf6e124d0581aec8c6545e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "026246a13c89c1a62f695bc05d5828eb69d9e2ec230f7954edeff6fb6384aec2"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.aarch64-linux-musl-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "d3ea15f761cfacbb4056489271ea28ba49098279"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "df4cbd4ad99c1f317c3ad93a2500c894a70b881e4339d3cc05662481209b258a"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.aarch64-linux-musl-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "69868dba5c6dfd2cbfbacfa19fbc6c9f21c5b144"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "07150ed1ffd80a8661432f09e3048b052ebf7e9f580c3032f2f89726364a5c8f"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.aarch64-linux-musl-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ad65505657e8d131cbafbe43d46e7c8982766bda"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "d6c3638699efa664c9e3d554a6b5992e5ee5fa41722d91df1850ddd190890913"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0756885bfac5f9eeda8b71d79b09895fd8e09e91"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "63a1bc4d78d82ff815bb4bc768c6864fc1c75bcf2c2578d55354f37fc715e43b"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "739f407a9dc4aee59f2d723d064f6edbf9878fca"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "003b83ad240430e6e9b049590c22aaff486319066d1f47107d4e7fdc39de73d7"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "93d8a6065eff60265f69cec8b85edb1bdc295dcc"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "cec58521560d565fb8bbb3c9003270458e7b3c61bc58f4a5b886a8ad375aa48b"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "acefe2d5d4c2c30be1594c79add0344d3e38bcae"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "238a7761ae01930aa670d69d1ad8395b96b84b7428275bcfc60685459cf18f86"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9a3e1533751c9018cdc8137dd8f1dfba9a9d7901"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "6e6f896d34541fd487afc897d338dac633156fa901c2d72db991be195f8781ad"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8fab1a9473cf1a1a8856fc7de2a2f3c821da5823"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "73cc698b74a0f9cc84b7877d9144260656ae5bc2bd309d41f6e8c051d6604fb1"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b33d4f1df452a20a0e5d063b52d7118aded72b06"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "d848331e11aeb1eb53da52004eecdd050bdcd3d905a6931d6f3db3956d699139"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "540d6442eb5886ad7ed7449e50c7b61b6ecc7025"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "5870d87905ae3ad5aa86821cea195e1c187f1e4a7e90e998ecf5c7a90bcacbd1"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "53cb96415d5ee6206398f1c61713a335eb3b819d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "aad61e9975372be6e32a96c4b07f629e4aba243ada1c0e1c0650bbafcf64c230"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "518c5373814b6467b6d1525ecb258f540d1ecd7f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "06bc3e66c02631886029df1f9245dc5eebf73508e64a18b0833070c71b185b6b"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "615372fecec6c2665ec71064bbc59ae555536a3b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "82fc5dea101e96f1802e63e04299d99ed1004e34f67cbaafe14b8aac5aad6ee2"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "b1090fb8936009159b8585d336fddcdd6d06179b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "9ad2a273d069fe19bcfa912caf349be386c6af3ba399fef17bd24cf34083a8db"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.i686-linux-gnu-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "8e637a10b7f00bad6de85e55782e10dfc131aadd"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "0e02910d90474347a5bcecc92d728b6b9ec1955c2b3c976d40cec0e0ee1dfbaa"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.i686-linux-gnu-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "84010cc7cc09629566b1ad2edfa2d28fef11ad01"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "1b61072aa2dd348143764cd85f8ea0d49557b23af10af359d284daf6530c745c"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.i686-linux-gnu-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "1ce3f5e2ba48cf0cc15b37500ec96744d63ba312"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "08c344d09f1aa3bb7c6809c3c4c390243c9520c9789268522f7304a6b31efc0e"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.i686-linux-musl-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "d9618001a28cd73af6b24535739026bdec0d9d4b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "0135be6428953586c947e58068d2b0d68897da617459e650aa4eefc73b37b889"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.i686-linux-musl-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "ac1bb8c5105b8d24d8f65b701238db36615409ce"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "d230f95f266d8a73e2fc74051720effdf329fea4f7f28535852b31fc9ecb2b24"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.i686-linux-musl-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "e69705f9e98b78fde4803e916c8893f949edf85e"
libgfortran_version = "3.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "a6d610a6228936b786aa4263bd8dece7a1d43d425564183097481c05751fd2f7"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.i686-w64-mingw32-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "107276ac752577fda797ad35913acbc984e05f80"
libgfortran_version = "4.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "e2a6712adbfeea6334c0c56545c3196a9b5a1167aee9e722f393d16f7ec3806e"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.i686-w64-mingw32-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "f87c3183cb6378de64e5d49fd3c77ecbf3c8cf1e"
libgfortran_version = "5.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "1e8b360fcfd75a675a42f30fb6ceb994e31614bdc8fa5c8a4173b03680706f83"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.i686-w64-mingw32-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "powerpc64le"
git-tree-sha1 = "75cb4f6e52a3be5517bb82885619f5f0f89f65ef"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "d3f861436cc9d257e9c3c335b2610d3517725d5db31f7480b17aa41820e0c5fc"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "powerpc64le"
git-tree-sha1 = "5dd664661110b25c458eaad841c7417396f1cba9"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "7a94b947bd54ed233d1acfb1e1da840915a2370c4c7894957a5400b6bdd31e75"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "powerpc64le"
git-tree-sha1 = "8d5be0c9461039d5ae9a05754e6ad6cbc0b3829b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "dfbdc896186ef8436d5e15a5238980a124c8a5304833345166f4834d5d647f74"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "4cb3c070c0c14406d5f24d9631c3cc0c4486b3ec"
libgfortran_version = "3.0.0"
os = "macos"

    [[SHTOOLS.download]]
    sha256 = "1a563450a14991a151065dc845a4a89d5908edb7f3d2b5a1963ebb48cb54ff0a"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.x86_64-apple-darwin-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "9638e2f76dff99c8a26c852da2b74c5e64961030"
libgfortran_version = "4.0.0"
os = "macos"

    [[SHTOOLS.download]]
    sha256 = "e9ebe2d3ee5b1e857104c9acfd9cec020e6ea2fc0a0d24cb5c1462813a826748"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.x86_64-apple-darwin-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "2474c7a66a9ce5536fe5fec0c4eae6b51eef3dc3"
libgfortran_version = "5.0.0"
os = "macos"

    [[SHTOOLS.download]]
    sha256 = "40821613173a2a99f5ea7325bb6be750d6dce206866582f381b8128f2ddc1cd2"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.x86_64-apple-darwin-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "734ad55e3164f7bef79076a0f58718f73379b2dc"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "8ae638cb93bbc294c96c535ae206b6b67cc6816fe0a3f105646a02c5b38ed8af"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.x86_64-linux-gnu-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "b155003e79abd8593d11f10c6b551f2df45ea263"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "49e02d4230f3c6e2a3e69ecfd81fae8c0d6a1528e879416228a35cc9a2574aff"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.x86_64-linux-gnu-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "a35939512f4cf4cae463515b06964899a9bd5d34"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "b5d77dbf119a1afaeb572f1a24530fd230d57c6d04979b7ceccddbe9e7dfc386"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.x86_64-linux-gnu-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "0fd97e5e0e01a478d854defa8f5cc6768eaec41e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "88f23729a9b0ff1ec762a8e9edda0d91d492396dbd49d366004e45c90d066fe9"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.x86_64-linux-musl-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "2ebeec81c0fb9567cfb5d4344eea4c4e8ad06e4c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "180c80d4027a05abfbc9951244685a117d79ace7a0be02103152e911b0d7f544"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.x86_64-linux-musl-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "46ae51e77556bef5e40219c0e32cdff155d501a8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "29f441e9c2a7157ea8e6f8c49b20dbb6036e74cf7b8b395bff40f692bd114d0b"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.x86_64-linux-musl-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "d2c9738dc95c420af37594b45df7615f3438165f"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[SHTOOLS.download]]
    sha256 = "14c0f2f3887301fa057b75de13d63a8ca6113cca6ca127e3fb9b607d76738186"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "8fdf02a817bfb8bdcbf928753cece7607a4e2817"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[SHTOOLS.download]]
    sha256 = "5dac9f45a10ff29320083232546d450caaba6f4b51afe1a29a579703552f37cc"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "0c70cd2abbf0f6a1d1b85495dbf1d922d08f41d6"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SHTOOLS.download]]
    sha256 = "bb63c63653f4b2a1cfa993b2b6c5ca24597923f7594fa701368fb6436301a078"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "366769a42ac733b2586453aa94b13aa03c8a7042"
libgfortran_version = "3.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "1c23df6296f9479d964236083e3134d21a934b4a2bdcdcdaee0e2c63b70eb279"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "a80e3b935dffb6a17a6dbc1c9cb9deaa197b2a34"
libgfortran_version = "4.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "6d0c2210a539724ab7f0ee007935a86996c33b26ed180c0a8c96f0a8a1e1ea8b"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "b8df0f64ebf73d226262ee6d1e5324018265fd61"
libgfortran_version = "5.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "7913bc3086367697189c9b55ce32222a9f4b07ddc9fdfa40d8357edc5b1d3f7a"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.4+0/SHTOOLS.v4.10.4.x86_64-w64-mingw32-libgfortran5.tar.gz"
