[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "49c9214b43f22ce324963a1a1ba06da9c7bedc4b"
libgfortran_version = "5.0.0"
os = "macos"

    [[SHTOOLS.download]]
    sha256 = "c27cef987523a80aadc4287e605e382a8296adf005e5f735d40e5d43636412f4"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "ec350d0edc20efddc040cfa7e164868be1bd4d16"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "845397d9360acb878b383943210d086c9f5402ee1d935d5f3ddfab722f3d95ea"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "ea6781d2321322aeff175bf7982494a5cb8871d2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "7ceb44cba2faefa11a16bd9a297ff9e869b4462d19edad863a454f4b95a32029"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "b3814565def906db89ffce1afb459e9203cf81c2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "7407bbfe0355d2261bb071e0345b8096f238e2c06ec3b463a6f1b65b249fbf02"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "4a46da2d4023bde02a422f5dfaabfb5501208771"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "3100ec03b29aa31f334139a219c571b11d90b3263f33e1f3bf589b96e0eae430"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "cfda5a2bd99d8d97d756641b5edc00b8af1ee490"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "cea6f03aaec0f0c2711d3b12ab2191a1bf768abebaf3293e1ffea1d8e3fb5b10"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "3465f86e24389a007328591af91be70d5524977c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "017cc837a2d50801a97aea447c39733abf0a3a6b9df8aad4c1ff62853c8deeb0"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bd6af34dca49b56e76f37d359ea4102794d07b9d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "f25bb79a8c23838459756da84b83df37a8f95186a1445c56e8c32f925666cb5d"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "93755e87906a17826dae54fed34f2fa12b7e72ed"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "5511a78f1f23bdde2c9f71df12aafa854b837940c2dbcec428b4b968c54ca50d"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "85fdcec3dcebde17f8b82779ca64c92c9c97e241"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "e72eae410e6edd06966feb0cc1a0485b4a7e6be8ebba482e39713934232c1fd9"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "03ee64387c4f2fd3d86cadc78b6117a77ea6d084"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "08b2ea913094b4eab30a17523a11917e8000305630cb2595353c09e429e54a4c"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f2a38f9ebf10c4f025c95fe0a90c93b3f2930f67"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "5110fcf60704ffd4f60a8be24001de4a4e2720620c71a750e1e10aeb63f78a0a"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a761c646011604e7304f48c29123aa0d7e549a7c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "6c993a90cf2041abe0daf53638d0121ca14d1e77e2c928e739c440635d3cc959"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "80f2304c9b8c0c6b425fc595ba2b2fda52197807"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "2a5f267f25d62d733afca62dc79b74ede865cbc4b49ab5832cb231ef4700e64c"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f27bc0a88885fe284655aae6a7ab2bf7da71001d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "461eac80787c7bc0423d00da9762c90fe39bd384e1ba16b53d10e620077ccc02"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f16936af5b952972fccefaaa12af1252a23ceed0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "89944ec98b2205f518a06d4a83129ea2f83d4acf2c94c73cd831344e5a23bb9f"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ffdcd9858f901577b0da9a6074429d412e0c3023"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "9062f03177a296151675a7333a28909f78fd49c85ec117436f70e852a5084eb9"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "91c3fe6122ee668b1802202c48ea460934752389"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "f81ce8c58aeb3b1616315139b0ca75838addae3a686273e05a8f4ba912b7b4ba"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f567924637a235151688a9bc22da9ea5cfbc6705"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "f97a05dd855cb250450e1580bd1dd827de61c4b9cb729d4a74b0fd02e42a3c47"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "514fd4a21843b72c54eac93053ad2ea2a33e8887"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "446d73ab39718d30c8f34616c31eab5380db42ffdb97b86e5310cd739c340ad4"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.i686-linux-gnu-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "b6e070a9dbc8ecb4f166524641c9568b64c9e996"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "fe99fae6ed2aef8068352b542959d9d85dee942b6884ab26a524fc4bfee63c41"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.i686-linux-gnu-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "9d0c0d52cab61f01cb5058b6d6b3e5505ce55d41"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "e765e88bf318d0dd7dbc1c2185886cd60faa48215672f17cef194f4230e5c4d3"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.i686-linux-gnu-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "2380a92e7fcb8e6620f60e82e77775fd7e060354"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "9bcb48b8c15222d1a69c731bd85b0508a991d7ea5d4619cd1d1cb85ebcae9b0c"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.i686-linux-musl-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "405e52400442e64eaa8e8932ae736513d06722bc"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "b642c6cd63bffbfb6f27af561b4b82f50d6b589cec394760a60f3b022cb422f0"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.i686-linux-musl-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "7510f02d9b37f3fa6816ef21f54fc8eaf378ee6e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "6c096329306753a7630ae662f5c30191ad805787358165a1240994057ac2c97e"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.i686-linux-musl-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "f6fc699f58c46d5fa1697af69009d1178cc0e6fe"
libgfortran_version = "3.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "67acd9e49b16b0932b2676791de0b05b112353379bf7ad16ee690276f7d02fb7"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "2e567c6d157143553b2b868c918301a68d78eed4"
libgfortran_version = "4.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "8fbe4046fbca4ede1cba5a95e2664aed5c1cc031106099b1dee6e1d175251943"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "38d68561ccfef35e2548c3f83e25b6952efb798d"
libgfortran_version = "5.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "dfc1a1573a8cb94d7582e4113fe4a9c9863adb7786328d97bcf610a3f44406bd"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "powerpc64le"
git-tree-sha1 = "6dccf6c6ea403f23b6d34ae54e104d2db3acccad"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "786e81bb83b2e42ab00bf9aa5ea7144a32349bc83edb95439de016782c7a757b"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "powerpc64le"
git-tree-sha1 = "cb5bed2931000e448628a9daaf28d45877df502a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "b73903de4a6b676d93a9e98a59358328a37fd429d24729507c9a0c09b6d47e94"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "powerpc64le"
git-tree-sha1 = "84b7af1ff199e39fd3edcbd0959a9f81685d3a82"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "71b2118097887c19fbe5011f724bc7de1267bcfcd1be28cc0cc672611306cbce"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "f1d1b04a6dd497d559fc592f2712da2afa8bddc4"
libgfortran_version = "3.0.0"
os = "macos"

    [[SHTOOLS.download]]
    sha256 = "bc5c8e4b85882126532312b8ea4f3cee5a71d96e7f72daa644d425a5cb6e51c6"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "ceaf8ef4cd44888cd4d775f8bc5cb983e9c81c1c"
libgfortran_version = "4.0.0"
os = "macos"

    [[SHTOOLS.download]]
    sha256 = "b01625d702068f43a227fd2bdfdd22d3236411357b1397c5e3a2c2eb8dc1e939"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "96d59311d480c77fceb303abe0b37a8d1dba45ce"
libgfortran_version = "5.0.0"
os = "macos"

    [[SHTOOLS.download]]
    sha256 = "a2cb0f5e955f543e7f0fc6f246308aab2009182d32e90e7b85e50dec3e39214a"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "f701371af92351f4b0a74c11846307047ced83bb"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "d54f994bb3a8a5dc86cb7390645e593ad59df2e70ef19ab89c874f495723c7fa"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "4cff2466424bf5c97c63b3c2647f30b8aa1109c6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "754f723b1c6ad3d90dd92af8f5bf7b370c4a7182bfa111775a24014f26161b81"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "61e9841e02a1ec2d34d84b6958fa5980160fc79b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "7a3636c1053bd0602d35d78e14e192816ea8fa880cf32e05a74cf46c8c2f2605"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "09845d5e7bef61d3bb4c2fad88928706c2dc6195"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "fd5e46dc3774fbfc456fbeed895c741b2957e4293288da49f6c33b04d9eb4eea"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "d51fb0ed450e6d350a6cad406752366fa4acba7e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "99d83048554aa868c4f9a4b0e4956521ffe93560aa5e0fd130680755cbd621f0"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "9abe2c2c401b5d798654419bba087e651b09b771"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "b532b27a2d0190950c38ddba8c1e1e40a5d4a945c44d9bec52a63b0263ab8db0"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "9a95b6a784f186146e45b141ff760041a7adaa67"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[SHTOOLS.download]]
    sha256 = "499b49cc3b7d5a8f674b01595c30b3b51c59c91d0ee2767bd4b565390d78255c"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "28490eea9cc1f95d14885a861ca934d0dbf1f216"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[SHTOOLS.download]]
    sha256 = "0cf211587670efffa63ce486f5a3c1f1fdddfff1854ecd9167c31a2fbeffde8d"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "9c52ee992bd3d36389a144b7f2164269ef350d65"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SHTOOLS.download]]
    sha256 = "a590bb932239c9241866ed2cdb5d8260a90982cb17b7b7df24e6367a2ad8cf4a"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "e89bbb23e4dd8b47fe0f271d54a3b26ca04f4802"
libgfortran_version = "3.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "617ab35321c084eeb2afd5ec12aaddc1df0d3341b6d4f1511cc9845735e5e164"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "6d80077385f9585e3da3c0f48120ad43dffbca49"
libgfortran_version = "4.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "756025d675776a6fb1f319e543fff4d57860c4fa39b2641eebcacd1acf134ad2"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "15f07b2c0c9e762e8326c1ab0fd3974606ecac59"
libgfortran_version = "5.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "f0fb967729ff40e53cc2dddf2710056528eb9ee3fb1484a7181755e99c74a991"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.1+0/SHTOOLS.v4.10.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
