[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "c340723c1ff1197322dc754267b59add8bf58eb3"
libgfortran_version = "5.0.0"
os = "macos"

    [[SHTOOLS.download]]
    sha256 = "999e59edd65c45b20aa7bb3a77ebc42d52f9cce93695523bf94dfd1ebd71dc5f"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "7ad8e998c8d50ff98b6cd06310c12f32bfeee5bd"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "9f56d9b3cc8a3c8f1807d7278b603938d7030ff6915c8a5c3492b64fca6b4a1f"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "6267979ccf9e4dc7a94933a8205d51163f204a9f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "8c8fd8e849e9192085b5c10437287ac0a10e1756f18742f1ed2806bd3ab8b653"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "0583dc40079b81634f6a5f0a77e6050e56067632"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "51a638be559bb20af1b98203421d10ab51eff246b46e74c244369d140a200281"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "f2cd15d9d0b37e41716e8fb818aeb3669c02989e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "bd48c4d5173049bded2890a32f89812d29c4fb7a45e3ac6293a855c4d846e19c"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "4ef6eeb41a78410dffb7f85e612da13c592f1020"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "fb763614807b161b632d454784477aa3eaaf668ebb06483b65085e666656cee3"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "e1be251afe74a27637ba60f885ef3fb8ffd1a367"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "6d8c49ffbd32c1c519f86ed9b2def73e5aef6b7f2ef1d40c0b037c347c4dacad"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f7323c6fa234ad8bdada841f7801187042f2860c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "1a9ad55dfc4dd1dac43e8c9cf55bc9582addd3d0dd1714e5e17438f7e4d95532"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cfbcf06792aee158bdf083fde31a2a3abf6a3f22"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "8fd1629ca17fcb79ecedc10d35d67229b945dea131cb0f3b0953820b9a2a6864"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dfcec5e1d12b7b6385a4868349979f11d83c6a9d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "88506174b7d8cf06a1e133084e34ea54f69a3a392d108c94b73d52ec40269b05"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a1a090df3b87b45018fe4b686095a2a65f8de686"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "d95f61c0145fa1730bee391cc25fd9a6a3e41a11a111eccddef60c4daa681906"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "61474cf660de7f530f687b70ebce450504733055"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "f66995502f06cf596df1b8c54a177a01be865baf11acfd884bf0892e1e124e87"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "58947a8440d04c13e7cd82587dc1cd66f4e2ffa4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "07cae15cae010daa50b7fb2f6a9fa6bb78389782947321d57fccd0835ffeaf7c"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "aad51b83ba95e2a1a36da83e51c3a65a796740c3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "3c920fc52e59b5b2fd2b62eeacb066650be1d44624005f1251745ebc728b1c18"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6a2482a178606af65e9805934915168dc9c2b623"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "5e000ba7e4389e7c12e4f8d589b7fb04e97fb83245e1a9df9a256829f9ce9b2c"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "98ddf30f185b398f5707fc7978f222756fedb857"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "d4124e07b4c8cf9d87da249b513ca29bc8a54513d8ce8a3d0ad5ea78542a96ad"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e404d5d8c8695a8506e880b13cad6bc33ed27d84"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "af202e81359dcebc44920f09fa03b7dc62678663e1441815a4b16fed40cb8d40"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "40e526e2f375f392d92e045b85897f55cebbfc04"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "d34eb25dd1bc3a14418f8d6caf78c1a3b4b71b94ef77901473df28205f287060"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9c48dce7f9f26bf4783f626129628ec0ce761eda"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "7d7c122d9003ad737cec889f4928eaa43cedc647e351e96a551258d3b7a6ea5a"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "fb27dac26777b4cf7d15a1d92446025b6b1c1a94"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "e937e6d56feea90f98c93f8805bac78b973a4e66c5d9791504e9cfba53d37a29"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.i686-linux-gnu-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "2dacdc3fd4abde4496d839c69a360e4bf5a9f74a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "28a7ec4c7a16767820e15e6359bbd1ac2ab9e0dea70564a5332749b5e775ea06"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.i686-linux-gnu-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "c28022fef60602e4354b88055677e4cb506975a8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "b36568808c71a582a62aff84943bcf440bdad94734258aca78d0d8525d337b26"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.i686-linux-gnu-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "1c54ba08539f058c795db8261c57786381ea6a07"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "bcdb8427feecfabaf91d74cab3b27ecbcf6ebf38871fcf21d47490618c4fbb88"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.i686-linux-musl-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "49173ecec7536d26209b6888fc34ad4f0182d3ef"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "2acd85a4364f11e0924bc4f7ca925c4169d0f3abbd9c2e7e8eaa6d30645d64ac"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.i686-linux-musl-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "574041d9f5c4b83e061ac70f7e3ebcca69584d2b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "65a90c502c178d4076310141e7e56e1cf0e8a9ddba9fa5ba0c751f3a6bd2e7fe"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.i686-linux-musl-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "b631d5a7488a3536efc358712a88d0d7dc8d75dd"
libgfortran_version = "3.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "ec62196b674637d1063860fa00429061f80d27569dab0633fd77689f8d66d01d"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "ef205d196f7cdc99f14e2a8667b1429b7d69ddc7"
libgfortran_version = "4.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "0fbfbe941eacec349a995ee51e00f3f2366692112480097d9cc0da88b3645905"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "31bd2157abd81a06e9f45862449a84a4abdf908e"
libgfortran_version = "5.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "aae39c047fb1b86ba58c140a4fdc3a3e4f9ed85cfd2bd6ea463551b5f9212523"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "powerpc64le"
git-tree-sha1 = "ab0e00cac2be4ba92d3d6229d7a927cc4cc815c4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "f634f9734fa0fd3ca400db62f7d067063c9badb1f12105fd9809e01bd7bf4c08"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "powerpc64le"
git-tree-sha1 = "fdb972a8bd8d62ef5fdf7db976afffc990fc38cf"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "904b8dc40fc47b0abb91a44f39d28dde28f1458ea85b894d3203f3abd0163e60"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "powerpc64le"
git-tree-sha1 = "95ed7020354555d6e102d3f66ed402461f7670a4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "c6d5ec786966e4767a7cbd2d608b15b253587bcc5f65e7f53e20b44cba096e35"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "ec28e197db54ddc9cd55a748878cf8575d917d6e"
libgfortran_version = "3.0.0"
os = "macos"

    [[SHTOOLS.download]]
    sha256 = "eacb623ac58002e1955de9b3f7382c33f0e556feda25047e0327f31ad4cca308"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "0fd5c8a0d27b7e58cceb76edf54f6ce37562d597"
libgfortran_version = "4.0.0"
os = "macos"

    [[SHTOOLS.download]]
    sha256 = "294090a09e3fbccdd532da7331ed4cbe08e14200b41638e43defc79c3a84d6e7"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "5130421fd5b0f84a7f365bcd829d9b1c80727bd5"
libgfortran_version = "5.0.0"
os = "macos"

    [[SHTOOLS.download]]
    sha256 = "1060fa4f658c8e5b6291805b56b964ac220494ab7e3ab9e7c597db11d0c874cd"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "1781b9112e17e787c4bee14089dd3c2a80f4f93e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "f1ab59d52cb67fbd8aeb5f468d8d6f18a1127cf211bd1087116a469bbd30b220"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "16b4c2e69c4408b25cbc90226a80b887e764629b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "b681cbd46c6c43bcb2517b5b31270916bf7f758581eda6c740de5becab8c81f8"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "cbc5087f57a4f696d1fb027313e3eb1041fc7306"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "1b6d596196339ba42eb849d3c7d1c7b08eb821eee3462db1e54835af7de30486"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "893cd6d93b3dc686bd084fab5354d74cf0da1fef"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "6988e03e7e126819cf23ad1ad6c0949e0644b53a7ec078e4df86606037c6b4bb"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "428ec99e7e63cea20b6a8645e82192b5dd19f57c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "5792590414885736613f7ea9c0cad1601bf6894d43facf9a323d00c486ac4e96"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "f22760e863efe0706398bd60014dc6452a6988c7"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "f7138bc9f483e3fcc1b33982da54544b15c6324c3270a98568846378d8d3de19"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "6b0759eeb37cd48cd9e141c2ffd245fcd6e4599c"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[SHTOOLS.download]]
    sha256 = "73fbaed51075926c33324c40227bd8943688089b7aa9e0d400ed930854981480"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "2a57e1d5c07b96da259930d22556fbd048678b62"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[SHTOOLS.download]]
    sha256 = "f2d461ae634840d9063a4854bbbbe589df7c60cdf5f96effa2b6aec50ae4bd74"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "63ada847cc40caf849b89670b899acac8d2a656e"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SHTOOLS.download]]
    sha256 = "e3e49e5bf605650828018f8b0adbd705790001b063b6c91b6406793061ec8312"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "4fbfc6c4ff621c22efb5b88118d71088c121e80c"
libgfortran_version = "3.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "9cdb10983c031352e529277f5ffb71e0cd9a3a3ba1b80a0b4900788b19a6dd58"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "15ea3867e021a2875ea127b5278880e076ea920c"
libgfortran_version = "4.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "39d07e5b1bfc93ad56cd2a012a911186b4b0c24b0023c1850c68a909d4f7e79f"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "277858bd884e56083c1a275b1eb9096dc4fd7f35"
libgfortran_version = "5.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "f1ad7f52c2e086aed4222fe1fab2fa2032baf6030941cd53f68c6dc3b8c6786c"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.9.1+0/SHTOOLS.v4.9.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
