[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "2567f63957495f6ba87c850248b456b492942b96"
libgfortran_version = "5.0.0"
os = "macos"

    [[SHTOOLS.download]]
    sha256 = "070d2f1e2626911fb7a624d9a30948ac07c82528c69e7f38f6dad894c35a76a6"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.aarch64-apple-darwin-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "f11820f8e2807eb85c933be4f5ab125e6bd06f32"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "7eec5b5e2f260fa172151335facfbc563aafbe71e06d515d056f92e7990d6a99"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.aarch64-linux-gnu-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "0e997449da18ed4fcc3db0917d71e6ad295b4532"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "e1cf78d501dde87515b0f49da77e4bd15bb15f95a002a6f89592f3791877a053"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.aarch64-linux-gnu-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "bedc89a53b7b11d2b1608d41744e5306c205b89d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "be649e8270bbfe219ccccf0021c15984b2493ba10654df4dd15a93ee9ccc24bd"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.aarch64-linux-gnu-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "f3eadd3a288aacbc7c9bb6fc7c353070c2f23d4c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "263b542f5d474a1637e8a42718a167bacce79bd838df8e91ce043a856056931b"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.aarch64-linux-musl-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "b102370b55d9e1a73ed34ef35d94f1b769be65f5"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "f9fb58a51b3ec18e8bc15cadb112f3f87161ec9c8d8326ab01ca59288ff79ed1"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.aarch64-linux-musl-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "c2ee89b3822466138de062c07502406f54fe6d7c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "a373525ceede65536dc658938c554e458d52f4ba2ebe9a9b5586ff25f179d6bf"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.aarch64-linux-musl-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2ce991369e761f07eb7bd460d2cfe7d0546911af"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "8eefa94438d77bd792e126f695c7f0f0655fedd2e1907b402a800bcfdaeeaa88"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "eed8c84bd8357579accbfcf2ede95a9e37a84488"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "51cd70c205c7d271fe07593c2ee3e80e4b5e89e12f51019b209c58254056e920"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "18922116fbf2db91948bf860dc88bf72b4568462"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "b74c0594cfe20381518c96da489d502cabcba01c1175a580e3912bcdc5a4c477"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4dcc1558a19d17d42277e079e708c59db9211aeb"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "a733b9c0e991e9182059aa9c17f6874c960a9b58bced369c59addfb38d5d738d"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5e2de80658d6b6dd9fc1612c577014592e2f960d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "710f86c954e69bda786c695f736e35a62e7327914553b36f8d66e44f9f769f1a"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bf3e3bbb5a01643d80d851182ccd3935c3a518e2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "f42a41d5a3d4ca9fa627f8e894e1096d184ad0578cb9d4d178bb5ba5902b7b6e"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cb6e0c979236ccb99ba3633977d3692c58170a1d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "d756d075b7d7bd8310904a15c105597961f81dfbb990688cd7d686147dfa93ee"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "74a323bb417c2b1d8857cc2464c8b35acb19db3c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "fdaaeff3a04ffec4abbe9b3b00524def0be1c9fe986c25e3e69afe44c6e05b39"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ab31f0f3be4aeea54fae516fdd2961ae733d52cc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "cdea322326392006e782a3985c3c02007d331dc398136b8b218b2b771aedd10f"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e2e80fcbf7ced7c334d1d310fb477936535a660f"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "c4c176cb6510e578db492d438a5f8d2b3930e56ea7ad6a3da86b3123b2bf04e6"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "684ff6f6e063b4bc0b12c482862e40aaea7d39e1"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "60b34bf9ddc14f8a00f673643b04bea2ad301518411637b9164077ea249e37d1"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f9817885c3fe0dd8ecc24475d422a22e15133178"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "1bd4978f038f096d51aac75113653dd01f8b98f76b7175c5581dedb85818b05b"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "3e730cc10cafb86f285a92dc9168d597fecdf2d9"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "f283bd75bffabf7d5f250bfbbb818a3a62617655156fb1d354b2fff0dc07d52b"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.i686-linux-gnu-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "76b87785787a0f0bc199bb010e76257dbf9dd9b6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "40022a54fba3dafafc943689a76d3708da68abb7f4c0f44f16796c780a1f2fff"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.i686-linux-gnu-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "999d60b430e416079391c44d840aa32a62fde662"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "8e9f0f4c8dfbc5b905f43e66c82e8adeb2327ee0dc1cc6adab67b41d16179b0d"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.i686-linux-gnu-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "e62d15b9f36d8b4fe151aaf572a7e6adf9dbac98"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "d1b38163644a71174678cb0fcba4c225a6813f2dd9a82bb42a891089fa3440b6"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.i686-linux-musl-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "fc9383b40e3ce314f5bf6de233ff41d4977a255f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "c987b8bb80ea68571dac7234f350af5f8bd5e829554d8f4f386eef4279261b8e"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.i686-linux-musl-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "551d5306a4b204b6a0b7504e03db39abe4732991"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "57a6d19177037214852de16c2c67b5a1238543dc9b6f7e9a4f29728a44bc7ff5"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.i686-linux-musl-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "8da7309586448b7e48bf9b08f79e133658c3d4bb"
libgfortran_version = "3.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "9c580ba5a6beba7529d97b0d1a8e79d898434a4d6c3cd25fe6c1293011ec97b8"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.i686-w64-mingw32-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "8b079345c4668fe6f2d609fd484185f7c7b2b928"
libgfortran_version = "4.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "8ab77eea8768a6b3c25003b80525e1ff2efe4e1bc7eb87eff827efba9c35739a"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.i686-w64-mingw32-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "d68977ce7b4faddb5c18560da2ca3ca9bfbfefdb"
libgfortran_version = "5.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "f1582008b0f22b89f6fadeed9ea537c88802e9838ccde331038351a7e684b58b"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.i686-w64-mingw32-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "powerpc64le"
git-tree-sha1 = "c85a722bbb6b28d122969da389ae7142e23bee70"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "1876a1d17234eb555ffeab70c6033eef4d98a77a1a1c84fcd49e5e4077040bb0"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "powerpc64le"
git-tree-sha1 = "605902423e04f9edf3fe92de5f100be3c3892196"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "52f92a039c19d0fe38a8b5251b69e68949e04a49bb91d81061551526789c02de"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "powerpc64le"
git-tree-sha1 = "64e7274ef3e7ca32843ec4f36a45c5091f0c6ed5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "6443d5899ff99463aeb694c7ae53b2fa1dc6c53ac88c51aa75c3f4a1e7143e5b"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "cba49eb15249dc0e23cecc0e0969656d3989b8a2"
libgfortran_version = "3.0.0"
os = "macos"

    [[SHTOOLS.download]]
    sha256 = "c54cdfd2271e710db7e0ac2fb2ef7378110e08ea573ca22584a9c286be18e98f"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.x86_64-apple-darwin-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "caba18cffe49d5c51bb108acc8fed9ba3052de54"
libgfortran_version = "4.0.0"
os = "macos"

    [[SHTOOLS.download]]
    sha256 = "7510ecb9d7a1eb647eb315bcb35689c816467b254189f8c7a15a22c53c138a06"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.x86_64-apple-darwin-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "9b177334a0c2adbb85566eb676b6a621a5249821"
libgfortran_version = "5.0.0"
os = "macos"

    [[SHTOOLS.download]]
    sha256 = "1f0bde2dfed4f7a60920ac04de32765c31c7ef66c0669ac91bbefbfcf003ac80"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.x86_64-apple-darwin-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "328494aa587b888b6a3fe81f758d42348bd451e7"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "ba3ebe8c2dac769a3a708ff7553cec06684eb24b43380d25268d48b8410411bb"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.x86_64-linux-gnu-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "354c38605e7f279ad7dd0fbeae2b7d060445d840"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "062bc41ffbdd714207f2abd8389468cbb68d3b0f07f326714f37decec75d73bf"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.x86_64-linux-gnu-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "4a082b325785b35565d0da371acdc9f33a953c6c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "717009692f40da458b728e186761e93f77c294830e499ae487a6d84a13725a99"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.x86_64-linux-gnu-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "b9c0560f1f0a785b9f0baf418658169168aa1fc7"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "8c2c8e784763c5cea7075e677d99cafe37e6880a8c9ee08c27a9ae105c3e4018"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.x86_64-linux-musl-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "6d708e41f861ec49e7b8054e399882d614735b32"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "99ab199fc8ab4181a15b4f0b23b4d2ecd9f3890245cbe6d879c5eb75dcb25aec"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.x86_64-linux-musl-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "47df0a8e82b987594f244414fbe1e150db4c5f0c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "7b756d10b1d8c21d451b44588f4a86ca4b3a115676756ec3bc9ae9c2168c97e6"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.x86_64-linux-musl-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "f808f70ca6152fb429f0a5596f3c6122ca86a408"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[SHTOOLS.download]]
    sha256 = "2603d44ef550b0c06a22c023ba4698ef5d435e30eed24ae696bd12f7ddb06e4c"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "a20c7e730bf098a17f36096694798dc9b28cf2d8"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[SHTOOLS.download]]
    sha256 = "09b54978dd73f2f3f81d67b213256c8ec6793338440d92e140a1464eb865c79c"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "98d70512bfc7d4e2af23989920d8433f1e1f9e32"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SHTOOLS.download]]
    sha256 = "7ac215aa45eb5675137673b0f4653b1d5285757e736ec5452d4d58dc766c5ffa"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "a3d4e7a4f2e5ade4fc1bf400ab9a354f2b9d2da3"
libgfortran_version = "3.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "a3992d55955d03f5de564ed011e0f3bb183402a60947a06f11c04d23a1a34bbc"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "b30b53ea2d5641df3fc5600056761b7e432fde79"
libgfortran_version = "4.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "860280783be7546a5827241a79ff0752e03689cd77a904821034bde0339e1260"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "10d871c86dca005a8ad645a7cd319b564cce65fc"
libgfortran_version = "5.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "333fdfe3b437be6548205d27aba9a158998bf1f5de9bdc6d34acc8892eed6535"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.11.10+0/SHTOOLS.v4.11.10.x86_64-w64-mingw32-libgfortran5.tar.gz"
