[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "c3e22f71a89877da5e1a39a78158b53c903065d7"
libgfortran_version = "5.0.0"
os = "macos"

    [[SHTOOLS.download]]
    sha256 = "05904764c4ce191a3b78fcf50cb6bc2006dfe0559ff46f53a886f595eafa90fa"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.aarch64-apple-darwin-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "2352e62e1f0ed0f2eea851a43b533373b36dbf1b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "5a556bd1856f919ddf409a7998ad8bbe0c9711ac00b9e1f7fbfd3b08d27b0c1e"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.aarch64-linux-gnu-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "2698de942d6ef0f18d402a03051ce5d9815ad783"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "7c158e5a834eb2a0fbba74b9f3b021bcf566a505d65bfd4c273cbc17ce1d9c44"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.aarch64-linux-gnu-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "b79f56f8fb261a7987a2268dcdd044c74997aeaa"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "f20fc3d23c55754eb97afcf93039a3fc5627de77c12f3ef67dca76091a08accc"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "46691626e387e7c7e7a386c8c409d5e31cd0ed63"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "37601fee642f233d9117240f19ba4150ac68706a13f1c4d54348f8f5c976a726"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.aarch64-linux-musl-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "af28df580251dac5a0ea6495da46abe1ad9fd161"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "5ffcf2617f6ef6a70fa9463662fda009a2c8cad72e6e1c31acf0f5554eaac1b3"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.aarch64-linux-musl-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "341ef538bd854fd2ab7475da4bf7865b67b7fa5c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "b7dee121319b6a0911a1add62ea73e40aee54f899788821a30191f0182342252"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.aarch64-linux-musl-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f19bf2a28c007a57321d256070cc81e6f6bc90ad"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "ae722f6102c793e36428439e313d0191c2b62c50c0ae8f1f05338680d377b144"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fabd4fe23696b1b51aa07e6eb0cf8ae9ff3548b0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "ea99e4cc3594bcd2782951579f4ee3e6bf22ca72980b771e34f9ab1faeef6363"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b72e32c4ee9774478ed03aaa6d230b59201a7674"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "b5e07bd8c8ae9e613ccfc8cd74ecf5db9e022e45b9e811326fce3639d0e6f1f7"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "858e1d410f059678327789977fa65130ecd6d3f2"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "33a6b3c6a9524dbe6193233c966a44013fd595b71859b42e70518c3082b70e46"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f4bae9cf7a5f60fadb41c420159a5ec6b321b9c5"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "a0fe51474d763e17a8106b74571486d5c478d3f6abd66406664a44cd7f5a1a7d"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "071a4ac91afd485d5aa384caacca152b12ada621"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "504031fa3b4dca056cf0a0270601504f20bdb10fd9cd40d7ddaff2652382967a"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8991955126f1d82bda6600596cacb0b4857a59f1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "edec4132fa3678607f18aa0787b25e7fcbd308f1a715b5697c7f9923f1242cb4"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c6e1f02aabcb9e27ffdb589edb78ad04c6ee604b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "ef0e5015a4611349402db8ee7b31423f26323a190b29b13bc4aeccedfc5493a1"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "863feae5d4512e1a618048bf3b3fca6c24ee0f36"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "9e755f3d5307c82262f48c81e76d352a597ad5ea2cd578beb2da6e77ffbef0be"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "32067fdf9cda6e939a1eac1abd5484930be07628"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "560bd8ad7005abb0798ce3296b97a6559e2aeee046fc5bff70a70d92bcb60cd2"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a906f7af06462b50f7c9eee42848d76ae2883f79"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "55880074ae69ba27db623f12d2b3b379e9b3ee8f5b586cca83f980d4b081554c"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "78d2dc3ce4e984e1af96693a01acec35b3b863a2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "01973d1644023185234cf03d9989c4fc95e16e27d79490630f31650be714f05b"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "9af71521f8883c1711a8262f8b2c32fd911acb88"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "61b6c43eddabeac5130961a3a8631fa4d5521b68cf3bf8b159d0cd72cf651289"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.i686-linux-gnu-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "8cca53796ea19e958e063a3a7e813a892877d646"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "2f7ff95cde3cf5e184ee3b85db73bbdb0f53de334e0e03cdce94a45b326fa7c2"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.i686-linux-gnu-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "919cf864f585bbaf262f37bc30f0a1cfee1b6d98"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "0a42de9624637f226c1282f57c9f6d30dfff232c132307078a0c9f4e7e516f59"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.i686-linux-gnu-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "e10f75b4199fc9a241cb969ab22367593e5aa1da"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "2678672da994a1c49e3a6d394d51776f6547afb66a69a7c09a9bed098bb7b17c"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.i686-linux-musl-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "0f88821a9b3b31057c86b04a955392d64f1ce3d6"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "c64323f661ea13c7deb54a48c91639ef63642bf3ab2945de667c5d37cf2f2ea9"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.i686-linux-musl-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "3c2cc7f0eea8e13d84d010ec84745442b7168c71"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "6be4bd2bd0afd75c1f4a2ae17cce1510d2540f6f01496beba7902e20004d1c63"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.i686-linux-musl-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "77f4cb5c6fb3a930b6a77bf4f8eb8150dfcf3a1f"
libgfortran_version = "3.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "9b5c60fd2b0ce4f03888d0819868c9c77b7291bda96676f68211a4a697df4af8"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.i686-w64-mingw32-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "2bd4c0b941d99e53a3c4d504856b70d8985b33ea"
libgfortran_version = "4.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "94346498a78273b16586ce8cd6b427e1fd230f6d8a59f5c451238cf57c1444ea"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.i686-w64-mingw32-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "7daf563a546f65441a875947bcfe6ddb303bd30b"
libgfortran_version = "5.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "2bfcbe82eeba0a3cf566996cebdeb0784b3c0d0dce5b98be14175fd4204c741c"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.i686-w64-mingw32-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "powerpc64le"
git-tree-sha1 = "36edab28eb938e2fc8e278d44b3e65d7e79da319"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "1b3c176dba3f839580d49443d932512a9a895e0ab158e7a42401384ba71f0c66"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "powerpc64le"
git-tree-sha1 = "995488075aef612a394a5e4b941742bc90df724d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "4af63ea50a8b822e420548ea46eea480aa9a61110f067bfc6d0e92dc37562b76"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "powerpc64le"
git-tree-sha1 = "b2c1aa1e09cb494900a2e220046e9a635663451e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "bcccd1d6472da571ed895c63a2802399062eba04f805bf706d2959143cdc12f4"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "60a2daadf5e650280f5fb1bde596eb2c4312422d"
libgfortran_version = "3.0.0"
os = "macos"

    [[SHTOOLS.download]]
    sha256 = "31b3a808b47be91a69aed04bd37930ede75735be0367a547f379156f4e67c4ea"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.x86_64-apple-darwin-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "8fbf79332f579d9e5eb02107a7b7d4272a2e40f7"
libgfortran_version = "4.0.0"
os = "macos"

    [[SHTOOLS.download]]
    sha256 = "b44a3a696524aefce52f6ce974fb7df54ac1899576b2f709c473b726a724c66c"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.x86_64-apple-darwin-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "c0c5611f65ab0d2725ebdb9fde5fb593a981314c"
libgfortran_version = "5.0.0"
os = "macos"

    [[SHTOOLS.download]]
    sha256 = "a399d49259d7eada5b194380c9c6d99199eb22e629d1c705ee91965fbfe96284"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "5916a89214dcb4f5c5b8859d571a2ff78b2bb672"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "6ec6d110db275dde8ff4780c0601ac700ea1ae6176ae0c3fc9abfd3ee2c95fb6"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.x86_64-linux-gnu-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "c9fc29304047780f0faaf42067e52ea69b0da9cf"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "589a4414960b3c3020073096732025248d97b5bc65faa8e833461af5ee4757bc"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "b985884a429848a8b9289d33f59c5fe489edab8b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "a79dc1bbc4a691bac5265e236cfb5332e4b01be5d67a3998e38f4bc945d935cf"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "2c6e5ce3802edb68a855c7e942d14827650065ac"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "9fcb89f11faa937276fc4b4484bf71e69e76b588f7dbefe534ceb22d52ce4c81"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.x86_64-linux-musl-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "868c8d67f79a9525177ba40f84a9678c35cc834d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "4daef619342910476983a1b39870a736f21da45264a58b01437fb0a68c3e3889"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.x86_64-linux-musl-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "fe872f04f54926e3ba5a6acb28b52833747c454d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "51c766bc8848f9dff07c9d222b795c91141fc9536ea7bc1c5f010daec1663740"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.x86_64-linux-musl-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "05d9cff363ae3741de4009735df46c3c7f682827"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[SHTOOLS.download]]
    sha256 = "a70982e9cf7bf0307ae5d022b3695c493da05d15a0a2b2c61aa9b4abb66ae676"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "5533a8c257e0d379c8ca6db8336efccf15ab46ef"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[SHTOOLS.download]]
    sha256 = "a1ef63d7552fa41e5f0d3a66dcb08bcafec4224cd3e62bf147f2c2fb49ad7c12"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "50acd8e6f36dc151d5c803e1baed85068b312eb4"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SHTOOLS.download]]
    sha256 = "eedb13940f9b6a7a0d56d9cad3643d2fb6d961bd461c29c27946d1c5614529c4"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "e07ead207743be1d87def234128179b6e64c3aa0"
libgfortran_version = "3.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "b70b2510b75bc3a3d68712164a0c381bf3569833beda4f13155e6f8babe371a1"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "84f50270e0fb2b0e6c6fc3c8421480552c4ec1df"
libgfortran_version = "4.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "8327fcd68f032a252976851dbcd1473cfd163a0fba581bde56146df992bd772b"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "9acc3be36572964ef7dd66f92780d259cb243fa6"
libgfortran_version = "5.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "943739cba120e9085f179fdc18d5643920e9763bbfed9307b0cb94daa4107ee8"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.10.2+0/SHTOOLS.v4.10.2.x86_64-w64-mingw32-libgfortran5.tar.gz"
