[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "6739717055271aa1181b913862e9e48a69f6152e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "266270a5330624194d8f15ca5091d4a8f7baa074afa904350d6738366d85ac80"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "37aeee399e562965a2f2ff16a766e92b40bc3650"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "e8960e8d65d9ed51c3dcce861dcf82870d469b6aa1ffd494a6407ea450da4dd1"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "148c324034d489220b53528d9a8118d3ec259e28"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "49347607c8f276ec61020ec8c001fd05d4432eb59a3a5748addaf1033803a886"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "3d2cf35a07a0591f4cffe6013e0f06779eae1767"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "74c749b7b84a3663db6700c3d623ebc62566442d8267ce5d21f5d89fe2cb0908"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "4e3dd9ca90473b989a5eefee5bffe113bc511c0e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "5d68374f9959070f7a568b054c7643091c584477ce277ed562c94f487bf68adf"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "aarch64"
git-tree-sha1 = "d8e7c3b29f31a565b51fb0ca2e1785a654e33dbb"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "9e32a2892bc5f4bbcc3deae37e25b8017330022be2d63254a6627941a14e8737"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5f364c1cd1ef071fd6fc6c8335f573b91751cdf4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "56ffbbd5c463c335b8e5e0ab2951f201078b14cb20d2ba99224be68b540550ce"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "35110010ebdd8ab575ecaf5308d78385fd3afb94"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "9bda7e7c1246c261848bdcd6ca885e4f18a3353158824637c361e0f2373fff54"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bb79fe5731dec671b03ee7b76c98ec5b5d3fe091"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "533777eaa1d3215f74c1d85767c5b741b951bab2dd98ad737d6b13e243e317ba"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7b18ad3b7f6ab8c7430dbcbd1a05fd9f8db3eb5e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "1923b94ef2db004972db41a01393e6ebc5b256774e313a54dfef655539a3398e"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5c144b90bc903702e9317fab89f101ac222cb13d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "3df1f70436bedc6a2207dc647ebe43d5a0e09e70e02acb56e2ec61588f89ae38"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "be999f26dd21b41d1adf8805c22527ee2c5e3673"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "702ee4cdfed3cdc850055a05e24a65a492b4d19fa9c5d1df5cbf61f2ffabaeae"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "830922ac97848a93b3fc9f5bb82c21f90442565d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "6445fb1bec3663da8ec3ceeb8113d5616eda412b7a0f0e316d39c991e1eb7b95"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.i686-linux-gnu-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "e705ad3f05c899c52ad38c0bcbb8a0259ea458bc"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "a90aa718439bc9d255a25b9a9d11aa48f2f60ec7e0a5c91e21e39eacc396874d"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.i686-linux-gnu-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "8a676a1b2c226e6c570da1cf54e5a6cdbeb2e259"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "3acaf144da6bb8e9c7f0704afea61f123d7b88fbb410d5be160ccaf546cd1231"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.i686-linux-gnu-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "13957a5d792928ea7d1f3af2cf12e269d1ec3d1a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "ebaf76383f3e6d43a45d302403be1fda82c3260b8b6fac05957353033d93d5e1"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.i686-linux-musl-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "ae3add7d20ca84133fae21c84148a9784a35478c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "a0e6fccd2eed21ad698eba0659963be480b394797507e21172f9cee94ba01d0a"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.i686-linux-musl-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "142a4aaa9c6b1d684b0077db09c813b854096b71"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "4fb5e120ff404e72b003679b64f8e692de3bedf06cd287a755804a9af4bb89f7"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.i686-linux-musl-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "30d6157457ec31d0524acd44937507571550a62f"
libgfortran_version = "3.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "596bfe8b1d3f9258c27572047c85ee85147bbdc9a062e0cab5dc046cd94b9296"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "08ddf88ed06a20db31ba977ad4ece3f271259e5d"
libgfortran_version = "4.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "77a5460772d7a5f8cc9ecdccac4a8d43cc958e4816e5f44994f14af9dd10b490"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "i686"
git-tree-sha1 = "bbd87b151b6fe73caf85c900a0a1a21241701ad5"
libgfortran_version = "5.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "ac48c9ab9004c67a17b2419e829837e9eacb63e0b77be3fdf502c1a72625375c"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "powerpc64le"
git-tree-sha1 = "4f222dea7b89e0801e58423db6192f284915396d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "cb4918abee19194a157356c81ae461f512e2b2d27e73fc2acd0a4c704c082e34"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "powerpc64le"
git-tree-sha1 = "85084dfe567577d9162c2657caa317362dab7a4c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "f32eac4765347936d7e927944d83005c71487b7b2ea79eaa79068e1f0ec1c81d"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "powerpc64le"
git-tree-sha1 = "6893a5797d3c88567818194a7ccfa65d9e736447"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "328788ff1dbf10824b975fa0038ddf377c9d0c0176ee9b7b3afb7242e92c0bbb"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "86cf0857dc674fc7796ea2f1d752f997fea7fa4a"
libgfortran_version = "3.0.0"
os = "macos"

    [[SHTOOLS.download]]
    sha256 = "466e55fcf5568a4828a9dc48e2204767bb85ab6ca322287cfed128dbdcecd98c"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "7ef12ea821640b2685b9d929818f719429d890b7"
libgfortran_version = "4.0.0"
os = "macos"

    [[SHTOOLS.download]]
    sha256 = "1beaa69ebf88bc200975918cd2c08f4da4f9dcc15486056efbe9b66f94a81007"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "5420560c3e44195ea597149c4adddf866d280705"
libgfortran_version = "5.0.0"
os = "macos"

    [[SHTOOLS.download]]
    sha256 = "c947523ecb102ce7ceff2d953bb50e89000605b15fb7e314e11538a74315e672"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "068fa18db42f1da49853a563a69499b794ef8e5f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "583003203eecbf1a3f0238da38e985c739709d497bed7cb372223f1360c58dc7"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "5924bd52e3b4e995cd5f76d582af568202d5de98"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "0e3eb7b02834c7bb9f249e5f5d44558ad4a0f3bfcc1409ae091c67ca102e9519"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "97a62392b077444d09ab2f400d625c3ddd35939b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "845fc7b1fe7b22d6a15ca1c7100c9a4f9cd49904e446b37a7241f775ee23cba2"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "394ab95635f8adef2feaa5e6fa5e69b64b0e5c08"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "644ac0d91b6e8f0984b6e8e9a07afe70905471a8801fc696c4aa04b6b9963e47"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "fb4e231c575a07519602916ad784f0679777c4a1"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "b67e6b34e816b91188757374a821033f07cb3eb568b51b9d787c9fc35cf1c634"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "28535730899475feb2b4de29ec15e08d3497c2a7"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SHTOOLS.download]]
    sha256 = "30fe1c3e4a33b0563f3754b74874798e6e329f332a717be5c6af46d02eefda57"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "fac1a690abbbed5684e2a45faec2d8684576917f"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[SHTOOLS.download]]
    sha256 = "c291b139790ff12054da5afbf9d03a9e4eb2fc921ff5a17474316bebf908b8da"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "a6adfbb02b050af320ccd19483f5f6250c89de9d"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[SHTOOLS.download]]
    sha256 = "eda5d44ceed58be9346755d2e03b0acb95244746aff525d6fb693720a2636782"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "de2da29efc43a29ccaa60ad5b0a8e9f2d10d6158"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SHTOOLS.download]]
    sha256 = "4eeb5002e1ae1d17941d26a507849ffadcc9d3715762228e59929713c2666f8d"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "d86c16a9eb0703a7154026ddde53132b8f9be77d"
libgfortran_version = "3.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "77ee5ba7b8fb3630d2666f5404ef8c3984c628c03e9f00dffab4f032b0fd388d"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "d44e85fe6bdca8edb59902517cb6a7b7f0252376"
libgfortran_version = "4.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "b69c309a5043b57f572849301402d763beb018231f5c396f573e7419fc22f659"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[SHTOOLS]]
arch = "x86_64"
git-tree-sha1 = "94acd4e782d7efd170f5cfe7015b129f8fca8ca0"
libgfortran_version = "5.0.0"
os = "windows"

    [[SHTOOLS.download]]
    sha256 = "0f05e9b7f77493aeff5000a0c951f18672e0543e51d7e733a4436841ecab8131"
    url = "https://github.com/JuliaBinaryWrappers/SHTOOLS_jll.jl/releases/download/SHTOOLS-v4.8.0+1/SHTOOLS.v4.8.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
